# Generated by Django 3.2.18 on 2023-08-17 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_borrowedbook_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
