# Generated by Django 3.2.18 on 2023-08-19 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20230819_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowedbook',
            name='returned_at',
        ),
    ]
